# Generated by Django 4.2.7 on 2023-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(verbose_name='زمان مطالعه'),
        ),
    ]
