# Generated by Django 4.2.7 on 2023-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, verbose_name='زمان مطالعه'),
        ),
    ]
